<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>Glow_Up.Services</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Glow-Up.Core\Glow-Up.Core.csproj" />
		<ProjectReference Include="..\Glow-Up.Repositories\Glow-Up.Repositories.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.2.7" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.12" />
		<PackageReference Include="Xabe.FFmpeg" Version="6.0.1" />
		<PackageReference Include="System.Text.Json" Version="8.0.0" />

	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

</Project>
